baseURL = 'https://purple-pond-02454f010.2.azurestaticapps.net/'
locale = 'en-us'
title = 'Inglés En Voz Alta'
theme = 'PaperMod'

[[menu.main]]
    name = "Vocabulario"
    url = "/vocabulary/"
    weight = 10